projects:
  - id: ifmapcli
  - id: irond
  - id: irongui

files:
  - source: agendas/generated-agenda-seq.txt
    destination: /
  - source: agendas/ifmapcli-test.txt
    destination: /
  - source: agendas/generated-agenda-timed.txt
    destination: /
  - source: agendas/publish-update-example-agenda.txt
    destination: /
  - source: agendas/sme-user-logins.txt
    destination: /
  - source: irond/basicauthusers.properties
    destination: /irond
  - source: irongui/irongui.properties
    destination: /irongui
