projects:
  - id: ifmapcli
  - id: irond
  - id: irongui

files:
  - source: agendas/example-agenda.txt
    destination: /
  - source: agendas/ncpvpn.txt
    destination: /
  - source: irond/basicauthusers.properties
    destination: /irond
  - source: irongui/irongui.properties
    destination: /irongui
