"TrustAtHsH::Irondemo::Modules::Break":
  alias: Break

"TrustAtHsH::Irondemo::Modules::Nothing":
  alias: Nothing

"TrustAtHsH::Irondemo::Modules::PublishUpdateExample":
  alias: PublishUpdateExample
  config:
    ifmap-user: test
    ifmap-pass: test

"TrustAtHsH::Irondemo::Modules::DeviceIp":
  alias: DeviceIp
  config:
    ifmap-user: test
    ifmap-pass: test

"TrustAtHsH::Irondemo::Modules::AccessRequestIp":
  alias: AccessRequestIp
  config:
    ifmap-user: test
    ifmap-pass: test

"TrustAtHsH::Irondemo::Modules::DeviceConnects":
  alias: DeviceConnects
  config:
    ifmap-user-pdp: pdp
    ifmap-pass-pdp: pdp
    ifmap-user-dhcp: dhcp
    ifmap-pass-dhcp: dhcp

"TrustAtHsH::Irondemo::Modules::DeviceDisconnects":
  alias: DeviceDisconnects
  config:
    ifmap-user-pdp: pdp
    ifmap-pass-pdp: pdp
    ifmap-user-dhcp: dhcp
    ifmap-pass-dhcp: dhcp

"TrustAtHsH::Irondemo::Modules::UserLogin":
  alias: UserLogin
  config:
    ifmap-user: test
    ifmap-pass: test

"TrustAtHsH::Irondemo::Modules::UserLogout":
  alias: UserLogout
  config:
    ifmap-user: test
    ifmap-pass: test

"TrustAtHsH::Irondemo::Modules::VulnerabilityDetected":
  alias: VulnerabilityDetected
  config:
    ifmap-user: sensor
    ifmap-pass: sensor

"TrustAtHsH::Irondemo::Modules::InitPdpInfrastructure":
  alias: InitPdpInfrastructure
  config:
    ifmap-user: test
    ifmap-pass: test

"TrustAtHsH::Irondemo::Modules::EnforcementAction":
  alias: EnforcementAction
  config:
    ifmap-user: iptables
    ifmap-pass: iptables

"TrustAtHsH::Irondemo::Modules::PurgeMetadata":
  alias: PurgeMetadata
  config:
    ifmap-user: test
    ifmap-pass: test

"TrustAtHsH::Irondemo::Modules::InvestigationRequested":
  alias: InvestigationRequested
  config:
    ifmap-user: pdp
    ifmap-pass: pdp

"TrustAtHsH::Irondemo::Modules::SmartphoneFeaturesDetected":
  alias: SmartphoneFeaturesDetected
  config:
    ifmap-user: sensor
    ifmap-pass: sensor
