"TrustAtHsH::Irondemo::Modules::DeviceConnects":
  alias: DeviceConnects
  config:
    ifmap-user-pdp: pdp
    ifmap-pass-pdp: pdp
    ifmap-user-dhcp: dhcp
    ifmap-pass-dhcp: dhcp

"TrustAtHsH::Irondemo::Modules::DeviceDisconnects":
  alias: DeviceDisconnects
  config:
    ifmap-user-pdp: pdp
    ifmap-pass-pdp: pdp
    ifmap-user-dhcp: dhcp
    ifmap-pass-dhcp: dhcp

"TrustAtHsH::Irondemo::Modules::UserLogin":
  alias: UserLogin
  config:
    ifmap-user: test
    ifmap-pass: test

"TrustAtHsH::Irondemo::Modules::UserLogout":
  alias: UserLogout
  config:
    ifmap-user: test
    ifmap-pass: test

"TrustAtHsH::Irondemo::Modules::VulnerabilityDetected":
  alias: VulnerabilityDetected
  config:
    ifmap-user: sensor
    ifmap-pass: sensor

"TrustAtHsH::Irondemo::Modules::InitPdpInfrastructure":
  alias: InitPdpInfrastructure
  config:
    ifmap-user: test
    ifmap-pass: test

"TrustAtHsH::Irondemo::Modules::EnforcementAction":
  alias: EnforcementAction
  config:
    ifmap-user: iptables
    ifmap-pass: iptables
